import org.flywaydb.gradle.task.FlywayMigrateTask
import org.flywaydb.gradle.task.FlywayInfoTask
import org.flywaydb.gradle.task.FlywayValidateTask
import org.flywaydb.gradle.task.AbstractFlywayTask
import kotlin.reflect.KClass

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.1.0/samples
 */

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.flywaydb:flyway-database-postgresql:11.20.1")
    }
}

plugins {
    java
    id("org.flywaydb.flyway") version "11.20.1"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    runtimeOnly("org.postgresql:postgresql:42.7.8")
}

flyway {
    configurations = arrayOf("runtimeClasspath")
}

fun getProperty(propertyName: String, envVarName: String, defaultValue: String): String {

    // Check system property first (-DpropName=value)
    val systemProperty = System.getProperty(propertyName)

    if(!systemProperty.isNullOrEmpty()) {
        return systemProperty
    }

    // Check environment variable
    val envValue = System.getenv(envVarName)

    if(!envValue.isNullOrEmpty()) {
        return envValue
    }

    return defaultValue
}

// Authentication: Flyway custom tasks
fun <T : AbstractFlywayTask> registerAuthenticationFlywayTask(
    name: String,
    type: KClass<T>
): TaskProvider<T> = tasks.register(name, type) {
    val dbUrl = getProperty("flyway.url", "FLYWAY_AUTHENTICATION_DB_URL", "jdbc:postgresql://localhost:5432/yatrakulo_authentication")
    val dbUser = getProperty("flyway.user", "FLYWAY_AUTHENTICATION_DB_USER", "postgres")
    val dbPassword = getProperty("flyway.password", "FLYWAY_AUTHENTICATION_DB_PASSWORD", "toor")

    url = dbUrl
    user = dbUser
    password = dbPassword
    locations = arrayOf("filesystem:infra/db/authentication/migrations")
}

val flywayAuthenticationInfo = registerAuthenticationFlywayTask("flywayAuthenticationInfo", FlywayInfoTask::class)
val flywayAuthenticationValidate = registerAuthenticationFlywayTask("flywayAuthenticationValidate", FlywayValidateTask::class)
val flywayAuthenticationMigrate = registerAuthenticationFlywayTask("flywayAuthenticationMigrate", FlywayMigrateTask::class)
