package com.ekapasha.auth_service.logging;

import com.ekapasha.shared.logging.LogEventName;

public enum AuthLogEvent implements LogEventName {
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILED,
  TOKEN_GENERATION_SUCCESS,
  TOKEN_GENERATION_FAILED,
  USER_REGISTERED_SUCCESS,
  USER_REGISTER_FAILED,
  USER_PROFILE_UPDATED,
  USER_PROFILE_UPDATE_FAILED,
  ROLE_CREATED,
  ROLE_UPDATED,
  ROLE_PERMISSIONS_UPDATED,
  ROLE_OPERATION_FAILED,
  WORKSPACE_CREATED,
  WORKSPACE_UPDATED,
  WORKSPACE_DELETED,
  WORKSPACE_DEFAULT_SET,
  WORKSPACE_OPERATION_FAILED,
  WORKSPACE_MEMBER_ADDED,
  WORKSPACE_MEMBER_REMOVED,
  WORKSPACE_MEMBER_ROLE_UPDATED,
  WORKSPACE_MEMBER_OPERATION_FAILED,
  UNHANDLED_EXCEPTION,
  VALIDATION_ERROR
}
