services:
  kong:
    image: kong/kong-gateway:3.14.0.7
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_PLUGINS=bundled,pre-function
      - KONG_REDIS_HOST=host.docker.internal
      - KONG_REDIS_PORT=6379
      - KONG_LUA_PACKAGE_PATH=/usr/local/kong/plugins/?.lua;;
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./kong/plugins:/usr/local/kong/plugins
      - ./kong:/kong/declarative/
    ports:
      - "8000:8000" # Proxy HTTP
      - "8443:8443" # Proxy HTTPS
      - "8001:8001" # Admin HTTP
      - "8444:8444" # Admin HTTPS
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - yatrakulo-net
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:7-alpine3.21
  #   container_name: yatrakulo-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - yatrakulo-net
  #   volumes:
  #     - redis-data:/data
  #   command: redis-server --appendonly yes

networks:
  yatrakulo-net:
    driver: bridge

volumes:
  redis-data:
