/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface FlywaySchemaHistory {
  checksum: number | null;
  description: string;
  execution_time: number;
  installed_by: string;
  installed_on: Generated<Timestamp>;
  installed_rank: number;
  script: string;
  success: boolean;
  type: string;
  version: string | null;
}

export interface TransactionPersistence {
  amount: Numeric;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  from_account_id: string;
  id: Generated<string>;
  idempotency_key: string;
  note: string | null;
  to_account_id: string;
  updated_at: Generated<Timestamp | null>;
  updated_by: string | null;
  workspace_id: string;
}

export interface DB {
  flyway_schema_history: FlywaySchemaHistory;
  transaction: Transaction;
}
