export const DATABASE_CONNECTION = Symbol('DATABASE_CONNECTION');
export const TRANSACTION_WRITE_REPOSITORY = Symbol(
  'TRANSACTION_WRITE_REPOSITORY',
);
export const TRANSACTION_READ_REPOSITORY = Symbol(
  'TRANSACTION_READ_REPOSITORY',
);
