/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountPersistence {
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  parent_id: string | null;
  type: string;
  updated_at: Generated<Timestamp | null>;
  updated_by: string | null;
  workspace_id: string | null;
}

export interface FlywaySchemaHistory {
  checksum: number | null;
  description: string;
  execution_time: number;
  installed_by: string;
  installed_on: Generated<Timestamp>;
  installed_rank: number;
  script: string;
  success: boolean;
  type: string;
  version: string | null;
}

export interface DB {
  account: AccountPersistence;
  flyway_schema_history: FlywaySchemaHistory;
}
