export const DATABASE_CONNECTION = Symbol('DATABASE_CONNECTION');
export const ACCOUNT_WRITE_REPOSITORY = Symbol('ACCOUNT_WRITE_REPOSITORY');
export const ACCOUNT_READ_REPOSITORY = Symbol('ACCOUNT_READ_REPOSITORY');
